version: '3.1'

services:
  # MySQL Container for the User Microservice
  db:
    image: mysql:latest
    restart: always
    ports:
      - "3309:3306"  # Unique port to avoid conflicts
    environment:
      MYSQL_DATABASE: user
      MYSQL_ROOT_PASSWORD: Password
    volumes:
      - mysql-data:/var/lib/mysql

    # Health check to ensure MySQL is ready before starting the service
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 5

  # RabbitMQ Container
  rabbitmq:
    image: rabbitmq:management
    restart: always
    ports:
      - "5672:5672"  # Default RabbitMQ port
      - "15672:15672"  # Management console port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 20s
      retries: 5

  # User Microservice
  user-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/user
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Password
      SPRING_RABBITMQ_ADDRESSES: amqp://rabbitmq:5672
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

volumes:
  mysql-data:
    driver: local
